name: Image to Dockerhub
on: [push] # When pushing to any branch then run this action
# Env variable
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_NAME: ${{secrets.REPO_NAME}}
jobs:
  push-image-to-docker-hub:  # job name
    runs-on: ubuntu-latest  # runner name : (ubuntu latest version) 
    steps:
    - uses: actions/checkout@v2 # first action : checkout source code
    - name: docker login
      run: | # log into docker hub account
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD  
    - name: Get current date # get the date of the build
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"
    - name: Build the Docker image # push The image to the docker hub
      run: docker build . --file Dockerfile --tag $DOCKER_USER/$REPO_NAME
    - name: Docker Push
      run: docker push $DOCKER_USER/$REPO_NAME
    - name: Configure SSH
      run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/dev.key
          chmod 600 ~/.ssh/dev.key
          cat >>~/.ssh/config <<END
            Host stage
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/dev.key
            StrictHostKeyChecking no
          END
      env:
          SSH_USER: ${{ secrets.SSH_USER_DEV }}
          SSH_KEY: ${{ secrets.SSH_KEY_DEV }}
          SSH_HOST: ${{ secrets.SSH_HOST_DEV }}
    - name: Deploy Stage Build
      run: |
          echo "${{ github.run_id }}"        
          ssh stage 'echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin'
          ssh stage 'cd /var/www/html/web; docker system prune -f; docker-compose pull; docker-compose up -d --force-recreate'
